sudo: required

services:
    - docker

before_script:
  - sudo apt-get update
  - sudo apt-get -y install lxc-docker
  - docker-compose build

script:
  - docker-compose run --rm -d web py.test

after_script:
  - docker-compose stop
