sudo: required

services:
    - docker

before_script:
  - docker-compose build
  - docker-compose up -d && docker ps  

script:
  - docker-compose run --rm -d web py.test

after_script:
  - docker-compose stop
